<a href="https://colab.research.google.com/github/Krishnakumar-KKK/Krishnakumar-KKK/blob/main/Tensorflow_module2_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf 
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [7]:
string = tf.Variable("This is a string",tf.string)
number = tf.Variable(101,tf.int16)
floating = tf.Variable(5.01,tf.float64)

rank1_string =  tf.Variable(["This is a string","jhfjdkk"],tf.string)
rank2_string =  tf.Variable([["This is a string","jhfjdkk"],['kk','kk1']],tf.string)

In [8]:
tf.rank(rank1_string)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
rank2_string.shape

TensorShape([2, 2])

**Reshaping Examples**




In [18]:
vector1 = tf.Variable([[[1,2,3,4,5,6]]],tf.int16)
print(vector1.shape)
vector2 = tf.reshape(vector1,[2,3])
vector3= tf.reshape(vector2,[2,-1])
print('VEctor 2',vector2)
print('VEctor 3',vector3)

(1, 1, 6)
VEctor 2 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
VEctor 3 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
